### ISSUE TITLE
Address React Warning Invalid DOM property 

### ISSUE THREAD

**Issue by jenndiaz** [wwcodecolorado/scrollodex#108]
#### Description
The project currently has a react warning on load. `Warning: Invalid DOM property class. Did you mean className ?`

#### Files 
[chumleyCard.jsx](https://github.com/wwcodecolorado/scrollodex/blob/main/src/cards/chumleyCard/chumleyCard.jsx)

#### How to Reproduce 
- Open dev tools, open console tab to see warning. 

#### Screenshot(s)
<img width="687" alt="screenshot of react warning invalid DOM property" src="https://user-images.githubusercontent.com/63808889/196831508-8a34977d-9f31-4597-9c9b-99b59a4b9da9.png">

#### Tasks
- [ ] Address cause of warning

**Comment by a-u-m** [comment]
@jenndiaz I have fixed this issue.

**Comment by a-u-m** [comment]
@jenndiaz  I have fixed this issue.

**Comment by domsbytes** [comment]
We got a fix for this, thanks y'all. Feel free to checkout our other issues please @LucianeFernandesRoque 👍
