### ISSUE TITLE
Create a footer component

### ISSUE THREAD

**Issue by domsbytes** [wwcodecolorado/scrollodex#12]
Design and create a footer for our project. You can keep it simple and display something like:

 Scrollodex 2021 

You can use this project as a reference for footer: 
- site: https://frontendstudygroup.github.io/ 
- code:  https://github.com/frontendstudygroup/frontendstudygroup.github.io/tree/master/src/components/Footer

**Comment by CHNUTT** [comment]
Could you please assign this to me?

**Comment by manish-singh-bisht** [comment]
Hi @domsbytes I am interested in your project , just visited your website https://scrollodex.netlify.app/ ,would love to contribute.
Please assign me.

**Comment by jischr** [comment]
Completed by @jenndiaz
