### ISSUE TITLE
Fix console react warnings 

### ISSUE THREAD

**Issue by domsbytes** [wwcodecolorado/scrollodex#141]
Fix console react warnings : 

react-dom.development.js:86 Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot
printWarning @ react-dom.development.js:86
error @ react-dom.development.js:60
render @ react-dom.development.js:29670
./src/index.js @ index.js:8
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:7
(anonymous) @ startup:7
react-jsx-dev-runtime.development.js:87 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `JamesKCard`. See https://reactjs.org/link/warning-keys for more information.
    at div
    at JamesKCard (http://localhost:3000/static/js/bundle.js:2088:82)
    at div
    at div
    at CardsDisplay (http://localhost:3000/static/js/bundle.js:4416:73)
    at div
    at App
printWarning @ react-jsx-dev-runtime.development.js:87
error @ react-jsx-dev-runtime.development.js:61
validateExplicitKey @ react-jsx-dev-runtime.development.js:1078
validateChildKeys @ react-jsx-dev-runtime.development.js:1105
jsxWithValidation @ react-jsx-dev-runtime.development.js:1276
JamesKCard @ JamesKCard.jsx:22
renderWithHooks @ react-dom.development.js:16305
mountIndeterminateComponent @ react-dom.development.js:20074
beginWork @ react-dom.development.js:21587
beginWork$1 @ react-dom.development.js:27426
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performSyncWorkOnRoot @ react-dom.development.js:26085
flushSyncCallbacks @ react-dom.development.js:12042
flushSync @ react-dom.development.js:26201
legacyCreateRootFromDOMContainer @ react-dom.development.js:29575
legacyRenderSubtreeIntoContainer @ react-dom.development.js:29601
render @ react-dom.development.js:29685
./src/index.js @ index.js:8
options.factory @ react refresh:6
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:7
(anonymous) @ startup:7
react-dom.development.js:86 Warning: Invalid DOM property `class`. Did you mean `className`?
    at a
    at div
    at div
    at CassandrasCard
    at div
    at div
    at CardsDisplay (http://localhost:3000/static/js/bundle.js:4416:73)
    at div
    at App

**Comment by a-u-m** [comment]
@domsbytes I would like to work on this issue
