### ISSUE TITLE
start a contact form component

### ISSUE THREAD

**Issue by domsbytes** [wwcodecolorado/scrollodex#20]
This can just be the skeleton of a form in a source file.

You don't have to worry about navigation to this form yet, or have it actually accept submissions yet.

Let me know if you have questions. 

Reference for creating this contact us form : 
- front end: https://frontendstudygroup.github.io/contact
- code: https://github.com/frontendstudygroup/frontendstudygroup.github.io/tree/master/src/components/ContactUs

**Comment by domsbytes** [comment]
Yes perfect @Gaurangseven ! Thank you

**Comment by Gaurangseven** [comment]
Thanks, I'll try my best.

**Comment by soursprite** [comment]
Before I finish the form on something you all don't want-

[image](https://user-images.githubusercontent.com/1970533/197080317-57661973-171f-430f-a7e3-41baeedacc1b.png)

Is that okay so far? If so, I'll take this issue and add a form.

**Comment by jischr** [comment]
Yep! This works, can you make sure the formatting is ok on mobile?

**Comment by Gaurangseven** [comment]
@domsbytes if you need any help regarding app development let me know , i m app developer now
