### ISSUE TITLE
Create a data model and database file for extensibility

### ISSUE THREAD

**Issue by indigostarr** [wwcodecolorado/scrollodex#36]
By using a data model and database file contributors can add their details to the file, add images to an img folder and add styling to an individual className. This will reduce the number of files and static imports.

**Comment by domsbytes** [comment]
would a user be able to click on a link to take them to a website tho? I was thinking that each card would serve as a gateway to their own website ( I realize that no one so far has done that yet ... it's hard to get that context from the exampleCard, might need to create a new issue )

I do appreciate the idea behind this though.

**Comment by domsbytes** [comment]
oh i see what you mean now, I think it could def work then :)
