### ISSUE TITLE
Speed up image loading

### ISSUE THREAD

**Issue by jischr** [wwcodecolorado/scrollodex#49]
The images are loading slowly on the app. Some ideas could be:
-  optimize images/file size to speed things up
-  figure out alternative image hosting/storage idea

**Comment by pururaj987** [comment]
Can I try this one @jischr ?

**Comment by jischr** [comment]
Sure thing!

**Comment by pururaj987** [comment]
@jischr I searched for some methods on google and found that ImageKit.io can be used to optimize images in realtime.

**Comment by jischr** [comment]
this has been completed.
