### ISSUE TITLE
make the card grid look better 

### ISSUE THREAD

**Issue by domsbytes** [wwcodecolorado/scrollodex#50]
This should be done in cardsDisplay.scss.

See if you can make the cards be displayed nicer as the grid/page gets filled up. 

Maybe we need flexbox instead?

**Comment by domsbytes** [comment]
Hi @jayeclark ! It is open to anyone :) feel free to give this a try , let me know if you have questions!

**Comment by jayeclark** [comment]
@domsbytes Fantastic! I’m done coding for the day but will give it a crack tomorrow - very excited to attempt something a little more open-ended!m.
