### ISSUE TITLE
Incorrect external linking on some cards

### ISSUE THREAD

**Issue by mjordancodes** [wwcodecolorado/scrollodex#66]
The external links on two cards do not link correctly. It appears that if you don't have the `https://` at the beginning of the URL it is trying to go to `https://scrollodex.netlify.app/your-entered-link.com` instead of just `your-entered-link.com`

Cards with issues: 
- Rachel Thomas @rachael-t 
- Chay McCormick @chay-chay

**Comment by jpacsai** [comment]
hi, can I work on this issue, please?

**Comment by chay-chay** [comment]
Hi all,

I’m working on the issue.


Best,
Chay
