### ISSUE TITLE
create a function to sort the cards alphabetically

### ISSUE THREAD

**Issue by jischr** [wwcodecolorado/scrollodex#7]
cards can be sorted by github user or card file name.
(and reverse alphabetically!) and a button to initiate the sort.

bonus: randomize the card order!

**Comment by neeraj15022001** [comment]
i can work on this one.

**Comment by jischr** [comment]
Hi @neeraj15022001! Thank you for your interest in contributing! This repo isn't quite ready for contributions yet (sorry I didn't add that that to the README yet)... We are also waiting until our meetup event (probably Oct. 13, more info coming soon) before accepting PRs. Please check back soon!

**Comment by neeraj15022001** [comment]
Not a problem, but try updating README :)

**Comment by jischr** [comment]
💯  - just updated it !!! thank you!!!
